repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        verbose: true
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings==1.5.0]
        verbose: true

  - repo: https://github.com/pre-commit/mirrors-mypy # configured via mypy.ini
    rev: v0.942
    hooks: # passing args: [] ensures we do not silently ignore imports (default) and instead explicitly configure in mypy.ini
      - id: mypy
        name: mypy_metricflow
        args: [--show-error-codes]
        verbose: true
        additional_dependencies:
          [
            "dbt-core<1.4",
            more-itertools,
            pytest,
            "sqlalchemy<2.0",
            sqlalchemy2-stubs,
            types-attrs,
            types-jinja2,
            types-jsonschema,
            types-python-dateutil,
            types-PyYAML,
            types-tabulate,
          ]
