sources:
  - name: tutorial
    schema: $system_schema
    description: Data sets for running mf tutorial
    tables:
      - name: $transactions_table
      - name: $customers_table
      - name: $countries_table