name: Publish Metricflow Release
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  poetry-publish:
    runs-on: ubuntu-latest
    environment: Pypi Publish
    env:
      python-version: "3.9"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ inputs.python-version }} Environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: "${{ env.python-version }}"

      - name: Hatch Publish
        run: hatch publish
        env:
          HATCH_INDEX_USER: transform_data
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_PASSWORD }}

